version: '3.3'
services:
    maccms:
        build: .
        container_name: maccms
        restart: always
        volumes:
            - ./maccms:/var/www/html
        ports:
            - 8080:80
        environment:
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_DATABASE=odm
            - DB_USERNAME=root
            - DB_PASSWORD=123